project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m398_f23
  title: "MATH 398"
  site-url: m398.inqs.info
  navbar:
    right:
      - syllabus.qmd
      - ec.qmd
      - books.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true



